/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zhiyou100.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SmallFile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4504775123944820007L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SmallFile\",\"namespace\":\"com.zhiyou100.schema\",\"fields\":[{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"context\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SmallFile> ENCODER =
      new BinaryMessageEncoder<SmallFile>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SmallFile> DECODER =
      new BinaryMessageDecoder<SmallFile>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SmallFile> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SmallFile> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SmallFile>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SmallFile to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SmallFile from a ByteBuffer. */
  public static SmallFile fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence fileName;
  @Deprecated public java.nio.ByteBuffer context;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SmallFile() {}

  /**
   * All-args constructor.
   * @param fileName The new value for fileName
   * @param context The new value for context
   */
  public SmallFile(java.lang.CharSequence fileName, java.nio.ByteBuffer context) {
    this.fileName = fileName;
    this.context = context;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileName;
    case 1: return context;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileName = (java.lang.CharSequence)value$; break;
    case 1: context = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fileName' field.
   * @return The value of the 'fileName' field.
   */
  public java.lang.CharSequence getFileName() {
    return fileName;
  }

  /**
   * Sets the value of the 'fileName' field.
   * @param value the value to set.
   */
  public void setFileName(java.lang.CharSequence value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'context' field.
   * @return The value of the 'context' field.
   */
  public java.nio.ByteBuffer getContext() {
    return context;
  }

  /**
   * Sets the value of the 'context' field.
   * @param value the value to set.
   */
  public void setContext(java.nio.ByteBuffer value) {
    this.context = value;
  }

  /**
   * Creates a new SmallFile RecordBuilder.
   * @return A new SmallFile RecordBuilder
   */
  public static com.zhiyou100.schema.SmallFile.Builder newBuilder() {
    return new com.zhiyou100.schema.SmallFile.Builder();
  }

  /**
   * Creates a new SmallFile RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SmallFile RecordBuilder
   */
  public static com.zhiyou100.schema.SmallFile.Builder newBuilder(com.zhiyou100.schema.SmallFile.Builder other) {
    return new com.zhiyou100.schema.SmallFile.Builder(other);
  }

  /**
   * Creates a new SmallFile RecordBuilder by copying an existing SmallFile instance.
   * @param other The existing instance to copy.
   * @return A new SmallFile RecordBuilder
   */
  public static com.zhiyou100.schema.SmallFile.Builder newBuilder(com.zhiyou100.schema.SmallFile other) {
    return new com.zhiyou100.schema.SmallFile.Builder(other);
  }

  /**
   * RecordBuilder for SmallFile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SmallFile>
    implements org.apache.avro.data.RecordBuilder<SmallFile> {

    private java.lang.CharSequence fileName;
    private java.nio.ByteBuffer context;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zhiyou100.schema.SmallFile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileName)) {
        this.fileName = data().deepCopy(fields()[0].schema(), other.fileName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.context)) {
        this.context = data().deepCopy(fields()[1].schema(), other.context);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SmallFile instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zhiyou100.schema.SmallFile other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.fileName)) {
        this.fileName = data().deepCopy(fields()[0].schema(), other.fileName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.context)) {
        this.context = data().deepCopy(fields()[1].schema(), other.context);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'fileName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFileName() {
      return fileName;
    }

    /**
      * Sets the value of the 'fileName' field.
      * @param value The value of 'fileName'.
      * @return This builder.
      */
    public com.zhiyou100.schema.SmallFile.Builder setFileName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fileName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fileName' field has been set.
      * @return True if the 'fileName' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fileName' field.
      * @return This builder.
      */
    public com.zhiyou100.schema.SmallFile.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'context' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getContext() {
      return context;
    }

    /**
      * Sets the value of the 'context' field.
      * @param value The value of 'context'.
      * @return This builder.
      */
    public com.zhiyou100.schema.SmallFile.Builder setContext(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.context = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'context' field has been set.
      * @return True if the 'context' field has been set, false otherwise.
      */
    public boolean hasContext() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'context' field.
      * @return This builder.
      */
    public com.zhiyou100.schema.SmallFile.Builder clearContext() {
      context = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SmallFile build() {
      try {
        SmallFile record = new SmallFile();
        record.fileName = fieldSetFlags()[0] ? this.fileName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.context = fieldSetFlags()[1] ? this.context : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SmallFile>
    WRITER$ = (org.apache.avro.io.DatumWriter<SmallFile>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SmallFile>
    READER$ = (org.apache.avro.io.DatumReader<SmallFile>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
