/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zhiyou100.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WordCount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5895283723409757567L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WordCount\",\"namespace\":\"com.zhiyou100.schema\",\"fields\":[{\"name\":\"word\",\"type\":\"string\"},{\"name\":\"count\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WordCount> ENCODER =
      new BinaryMessageEncoder<WordCount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WordCount> DECODER =
      new BinaryMessageDecoder<WordCount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<WordCount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<WordCount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WordCount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this WordCount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a WordCount from a ByteBuffer. */
  public static WordCount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence word;
  @Deprecated public int count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WordCount() {}

  /**
   * All-args constructor.
   * @param word The new value for word
   * @param count The new value for count
   */
  public WordCount(java.lang.CharSequence word, java.lang.Integer count) {
    this.word = word;
    this.count = count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return word;
    case 1: return count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: word = (java.lang.CharSequence)value$; break;
    case 1: count = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'word' field.
   * @return The value of the 'word' field.
   */
  public java.lang.CharSequence getWord() {
    return word;
  }

  /**
   * Sets the value of the 'word' field.
   * @param value the value to set.
   */
  public void setWord(java.lang.CharSequence value) {
    this.word = value;
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public java.lang.Integer getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Integer value) {
    this.count = value;
  }

  /**
   * Creates a new WordCount RecordBuilder.
   * @return A new WordCount RecordBuilder
   */
  public static com.zhiyou100.schema.WordCount.Builder newBuilder() {
    return new com.zhiyou100.schema.WordCount.Builder();
  }

  /**
   * Creates a new WordCount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WordCount RecordBuilder
   */
  public static com.zhiyou100.schema.WordCount.Builder newBuilder(com.zhiyou100.schema.WordCount.Builder other) {
    return new com.zhiyou100.schema.WordCount.Builder(other);
  }

  /**
   * Creates a new WordCount RecordBuilder by copying an existing WordCount instance.
   * @param other The existing instance to copy.
   * @return A new WordCount RecordBuilder
   */
  public static com.zhiyou100.schema.WordCount.Builder newBuilder(com.zhiyou100.schema.WordCount other) {
    return new com.zhiyou100.schema.WordCount.Builder(other);
  }

  /**
   * RecordBuilder for WordCount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WordCount>
    implements org.apache.avro.data.RecordBuilder<WordCount> {

    private java.lang.CharSequence word;
    private int count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zhiyou100.schema.WordCount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.word)) {
        this.word = data().deepCopy(fields()[0].schema(), other.word);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing WordCount instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zhiyou100.schema.WordCount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.word)) {
        this.word = data().deepCopy(fields()[0].schema(), other.word);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'word' field.
      * @return The value.
      */
    public java.lang.CharSequence getWord() {
      return word;
    }

    /**
      * Sets the value of the 'word' field.
      * @param value The value of 'word'.
      * @return This builder.
      */
    public com.zhiyou100.schema.WordCount.Builder setWord(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.word = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'word' field has been set.
      * @return True if the 'word' field has been set, false otherwise.
      */
    public boolean hasWord() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'word' field.
      * @return This builder.
      */
    public com.zhiyou100.schema.WordCount.Builder clearWord() {
      word = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public java.lang.Integer getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.zhiyou100.schema.WordCount.Builder setCount(int value) {
      validate(fields()[1], value);
      this.count = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.zhiyou100.schema.WordCount.Builder clearCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WordCount build() {
      try {
        WordCount record = new WordCount();
        record.word = fieldSetFlags()[0] ? this.word : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.count = fieldSetFlags()[1] ? this.count : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WordCount>
    WRITER$ = (org.apache.avro.io.DatumWriter<WordCount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WordCount>
    READER$ = (org.apache.avro.io.DatumReader<WordCount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
